Diffusion:
  model_name: "cagliostrolab/animagine-xl-3.1"
  model_path: "E:/OneDrive/Documents/Workspace/vision novel/stable-diffusion-webui/models/Stable-diffusion/animagine-xl-3.1.safetensors"

TTS:
  speed_factor: 1
  audio_format: "mp3"

CapCut:
  Host: "editor-api-va-us-looki.capcutapi.com"
  appvr: "4.8.0"
  pf: "4"
  sign-ver: "1"
  User-Agent: "Cronet/TTNetVersion:e30e5f0d 2024-08-29 QuicVersion:4bf243e0 2023-04-17"
  accept-encoding: "gzip, deflate"
  store-country-code: ""
  tdid: "7399120097476625925"