Character_Designer:
  email: llu430173@gmail.com
  bot_id: vnovCharacterDesign


Storyteller:
  email: yang_huibo@outlook.com
  bot_id: vnovStoryteller

Refiner:
  email: luke.yangluhb@gmail.com
  bot_id: vnoRefiner

Storyboard Artist:
  email: luke.yangluhb@gmail.com
  bot_id: vnoStoryboardArtist


Emails:
  luke.yangluhb@gmail.com
  yhb19991115@gmail.com