from .artist import (
    ARTIST_ROLE,
    PROMPT_OPTIMIZATION
)

from .photographer import (
    PHOTOGRAPHER_ROLE,
    SHOT_TAKING
)

from .storyteller import (
    STORYTELLER_ROLE,
    TELLING_INSERTION,
    FIRSTPERSON_TELLING_SYSTEM_MSG,
    FIRSTPERSON_TELLING,
    FIRST_PERSON_TELLING_PREVIOUSLY,
    NOVEL_FS_EXAMPLE
)

from .refiner import (
    REFINE_CHAPTERS,
    REFINE_SYSTEM_MSG,
    REFINE_GREETING
)

from .storyboard import (
    STORYBOARD_ARTIST_ROLE,
    STORYBOARD_ARTIST_PROMPT,
    STORYBOARD_ARTIST_INSERTION,
    STORYBOARD_ARTIST_ACT,
    STORYBOARD_EXAMPLE
)

from .character_designer import (
    CHARACTER_INFO_EXAMPLE,
    DESIGNER_ROLE,
    DESIGNER_PROMPT,
    DESIGNER_INSERTION,
    EXAMPLAR_OUTPUT
)

from .director import (
    DIRECTOR_ROLE,
    GENERAL_DIRECTOR_INSTRUCTION,
    DIRECTOR_EXAMPLE,
    DIRECTOR_PROMPT,
    BATCH_DIRECTOR_PROMPT
)

from .summarizer import (
    SUMMARIZER_INSTRUCTION,
    LAST_SUMMARIZER_PROMPT
)

from .evaluator import (
    EVALUATOR_INSTRUCTION,
    EVALUATION_RUBRIC
)

from .improver import (
    IMPROVE_INSTRUCTION
)